hydra:
  run:
    dir: hydra_output/

comet_ml:
  api_key: LSTIie51umcysQtnef1Zzil6V
  project_name: cassava-leaf-disease-classification

data:
  exp_name: test
  seed: 42
  img_size: 256
  n_splits: 5

train:
  lr: 2e-5
  epoch: 50
  fold: 0
  batch_size: 64
  num_workers: 0
  weight_decay: 1e-5
  model_type: efficientnet_b0
  warmup_step: -1
  scheduler: onecycle
